import { create } from "zustand";

export const useRoundStore = create((set) => ({
    currentRound: 1,
    totalRounds: 3,
    turnEndTime: null,
    isTurnActive: false,
    role: null,
    showRoleSplash: false,
    turnEndWord: "",
    showTurnEndSplash: false,
    matchWinner: null,
    showMatchWinnerSplash: false,

    setCurrentRound: (currentRound) => set({ currentRound }),
    setTotalRounds: (totalRounds) => set({ totalRounds }),
    setTurnEndTime: (turnEndTime) => set({ turnEndTime }),
    setIsTurnActive: (isTurnActive) => set({ isTurnActive }),
    setRole: (role) => set({ role }),
    setShowRoleSplash: (showRoleSplash) => set({ showRoleSplash }),
    setTurnEndWord: (turnEndWord) => set({ turnEndWord }),
    setShowTurnEndSplash: (showTurnEndSplash) => set({ showTurnEndSplash }),
    setMatchWinner: (matchWinner) => set({ matchWinner }),
    setShowMatchWinnerSplash: (showMatchWinnerSplash) => set({ showMatchWinnerSplash }),
    setClearCanvas: (clearCanvas) => set({ clearCanvas }),
    reset: () => set({
        currentRound: 1,
        totalRounds: 3,
        turnEndTime: null,
        isTurnActive: false,
        role: null,
        showRoleSplash: false,
        turnEndWord: "",
        showTurnEndSplash: false,
        matchWinner: null,
        showMatchWinnerSplash: false,
        clearCanvas: false,
    }),
}));
